using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EmployeeMangement.DAL
{
    public class EmployeeSeeder : ISeeder
    {
        public void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employee>().HasData(
                new Employee { Id = 1, FirstName = "Donald", LastName = "Baird", Email = "donald.baird1@yahoo.com", Position = "Software Engineer" },
    new Employee { Id = 2, FirstName = "Omar", LastName = "Peters", Email = "omar.peters2@gmail.com", Position = "UX Designer" },
    new Employee { Id = 3, FirstName = "Mark", LastName = "Clark", Email = "mark.clark3@yahoo.com", Position = "Project Manager" },
    new Employee { Id = 4, FirstName = "Jessica", LastName = "Arnold", Email = "jessica.arnold4@yahoo.com", Position = "QA Engineer" },
    new Employee { Id = 5, FirstName = "Cheryl", LastName = "Brown", Email = "cheryl.brown5@gmail.com", Position = "Project Manager" },
    new Employee { Id = 6, FirstName = "Adam", LastName = "Torres", Email = "adam.torres6@hotmail.com", Position = "Business Analyst" },
    new Employee { Id = 7, FirstName = "Mary", LastName = "Stevens", Email = "mary.stevens7@hotmail.com", Position = "Product Owner" },
    new Employee { Id = 8, FirstName = "Nicholas", LastName = "Meyer", Email = "nicholas.meyer8@hotmail.com", Position = "Software Engineer" },
    new Employee { Id = 9, FirstName = "Connie", LastName = "Carroll", Email = "connie.carroll9@gmail.com", Position = "Product Owner" },
    new Employee { Id = 10, FirstName = "Ronnie", LastName = "Taylor", Email = "ronnie.taylor10@hotmail.com", Position = "Product Owner" },
    new Employee { Id = 11, FirstName = "Stacy", LastName = "Carter", Email = "stacy.carter11@yahoo.com", Position = "System Administrator" },
    new Employee { Id = 12, FirstName = "Adrienne", LastName = "Williams", Email = "adrienne.williams12@yahoo.com", Position = "Software Engineer" },
    new Employee { Id = 13, FirstName = "Taylor", LastName = "Cox", Email = "taylor.cox13@hotmail.com", Position = "Technical Writer" },
    new Employee { Id = 14, FirstName = "Ryan", LastName = "Wilkins", Email = "ryan.wilkins14@gmail.com", Position = "UX Designer" },
    new Employee { Id = 15, FirstName = "Scott", LastName = "Garcia", Email = "scott.garcia15@gmail.com", Position = "Project Manager" },
    new Employee { Id = 16, FirstName = "Sandra", LastName = "Clark", Email = "sandra.clark16@hotmail.com", Position = "UX Designer" },
    new Employee { Id = 17, FirstName = "Ross", LastName = "Hull", Email = "ross.hull17@yahoo.com", Position = "Project Manager" },
    new Employee { Id = 18, FirstName = "Abigail", LastName = "Turner", Email = "abigail.turner18@gmail.com", Position = "Project Manager" },
    new Employee { Id = 19, FirstName = "Kevin", LastName = "Allen", Email = "kevin.allen19@yahoo.com", Position = "Software Engineer" },
    new Employee { Id = 20, FirstName = "Jonathan", LastName = "Jones", Email = "jonathan.jones20@hotmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 21, FirstName = "Gary", LastName = "Hoover", Email = "gary.hoover21@yahoo.com", Position = "DevOps Engineer" },
    new Employee { Id = 22, FirstName = "Justin", LastName = "Smith", Email = "justin.smith22@hotmail.com", Position = "Product Owner" },
    new Employee { Id = 23, FirstName = "Sally", LastName = "Lang", Email = "sally.lang23@gmail.com", Position = "Data Analyst" },
    new Employee { Id = 24, FirstName = "Diana", LastName = "Houston", Email = "diana.houston24@gmail.com", Position = "Product Owner" },
    new Employee { Id = 25, FirstName = "Caitlin", LastName = "Moore", Email = "caitlin.moore25@gmail.com", Position = "UX Designer" },
    new Employee { Id = 26, FirstName = "Taylor", LastName = "Delacruz", Email = "taylor.delacruz26@gmail.com", Position = "Data Analyst" },
    new Employee { Id = 27, FirstName = "Erica", LastName = "Robinson", Email = "erica.robinson27@yahoo.com", Position = "DevOps Engineer" },
    new Employee { Id = 28, FirstName = "Kevin", LastName = "Lane", Email = "kevin.lane28@gmail.com", Position = "QA Engineer" },
    new Employee { Id = 29, FirstName = "Jimmy", LastName = "Murphy", Email = "jimmy.murphy29@hotmail.com", Position = "Project Manager" },
    new Employee { Id = 30, FirstName = "Larry", LastName = "Thompson", Email = "larry.thompson30@gmail.com", Position = "Data Analyst" },
    new Employee { Id = 31, FirstName = "Ryan", LastName = "Ford", Email = "ryan.ford31@yahoo.com", Position = "UX Designer" },
    new Employee { Id = 32, FirstName = "Raymond", LastName = "Morales", Email = "raymond.morales32@gmail.com", Position = "QA Engineer" },
    new Employee { Id = 33, FirstName = "Steven", LastName = "Bauer", Email = "steven.bauer33@gmail.com", Position = "Software Engineer" },
    new Employee { Id = 34, FirstName = "Larry", LastName = "Vargas", Email = "larry.vargas34@gmail.com", Position = "System Administrator" },
    new Employee { Id = 35, FirstName = "Joshua", LastName = "Perkins", Email = "joshua.perkins35@yahoo.com", Position = "System Administrator" },
    new Employee { Id = 36, FirstName = "Gerald", LastName = "Howe", Email = "gerald.howe36@gmail.com", Position = "Technical Writer" },
    new Employee { Id = 37, FirstName = "Gabriel", LastName = "Sloan", Email = "gabriel.sloan37@gmail.com", Position = "Software Engineer" },
    new Employee { Id = 38, FirstName = "Danielle", LastName = "Gutierrez", Email = "danielle.gutierrez38@gmail.com", Position = "UX Designer" },
    new Employee { Id = 39, FirstName = "Anna", LastName = "Freeman", Email = "anna.freeman39@gmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 40, FirstName = "Sean", LastName = "Richards", Email = "sean.richards40@gmail.com", Position = "Data Analyst" },
    new Employee { Id = 41, FirstName = "Amy", LastName = "Clarke", Email = "amy.clarke41@gmail.com", Position = "Technical Writer" },
    new Employee { Id = 42, FirstName = "Emma", LastName = "Warner", Email = "emma.warner42@gmail.com", Position = "System Administrator" },
    new Employee { Id = 43, FirstName = "Abigail", LastName = "Mercado", Email = "abigail.mercado43@gmail.com", Position = "Technical Writer" },
    new Employee { Id = 44, FirstName = "Lauren", LastName = "Castro", Email = "lauren.castro44@hotmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 45, FirstName = "Anthony", LastName = "Martinez", Email = "anthony.martinez45@yahoo.com", Position = "UX Designer" },
    new Employee { Id = 46, FirstName = "Mark", LastName = "Hernandez", Email = "mark.hernandez46@yahoo.com", Position = "Project Manager" },
    new Employee { Id = 47, FirstName = "Ashley", LastName = "Beck", Email = "ashley.beck47@yahoo.com", Position = "DevOps Engineer" },
    new Employee { Id = 48, FirstName = "Ryan", LastName = "Wise", Email = "ryan.wise48@yahoo.com", Position = "Technical Writer" },
    new Employee { Id = 49, FirstName = "Alice", LastName = "Lynch", Email = "alice.lynch49@yahoo.com", Position = "Technical Writer" },
    new Employee { Id = 50, FirstName = "Amanda", LastName = "Gonzalez", Email = "amanda.gonzalez50@gmail.com", Position = "Product Owner" },
    new Employee { Id = 51, FirstName = "Gregory", LastName = "Sosa", Email = "gregory.sosa51@gmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 52, FirstName = "Matthew", LastName = "Barrett", Email = "matthew.barrett52@yahoo.com", Position = "System Administrator" },
    new Employee { Id = 53, FirstName = "Stacy", LastName = "Stewart", Email = "stacy.stewart53@hotmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 54, FirstName = "Glen", LastName = "Donaldson", Email = "glen.donaldson54@yahoo.com", Position = "Technical Writer" },
    new Employee { Id = 55, FirstName = "Justin", LastName = "Marquez", Email = "justin.marquez55@gmail.com", Position = "Data Analyst" },
    new Employee { Id = 56, FirstName = "Cathy", LastName = "Smith", Email = "cathy.smith56@gmail.com", Position = "UX Designer" },
    new Employee { Id = 57, FirstName = "Jonathan", LastName = "Baker", Email = "jonathan.baker57@yahoo.com", Position = "Software Engineer" },
    new Employee { Id = 58, FirstName = "Christopher", LastName = "Benjamin", Email = "christopher.benjamin58@hotmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 59, FirstName = "Russell", LastName = "Ellis", Email = "russell.ellis59@gmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 60, FirstName = "Elizabeth", LastName = "Jenkins", Email = "elizabeth.jenkins60@gmail.com", Position = "Software Engineer" },
    new Employee { Id = 61, FirstName = "Katherine", LastName = "Robertson", Email = "katherine.robertson61@gmail.com", Position = "System Administrator" },
    new Employee { Id = 62, FirstName = "Karen", LastName = "Smith", Email = "karen.smith62@hotmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 63, FirstName = "Michael", LastName = "Morales", Email = "michael.morales63@yahoo.com", Position = "System Administrator" },
    new Employee { Id = 64, FirstName = "Rebecca", LastName = "Cooper", Email = "rebecca.cooper64@gmail.com", Position = "Technical Writer" },
    new Employee { Id = 65, FirstName = "Barbara", LastName = "Robles", Email = "barbara.robles65@yahoo.com", Position = "Software Engineer" },
    new Employee { Id = 66, FirstName = "Luis", LastName = "Hill", Email = "luis.hill66@hotmail.com", Position = "System Administrator" },
    new Employee { Id = 67, FirstName = "Michael", LastName = "Turner", Email = "michael.turner67@yahoo.com", Position = "QA Engineer" },
    new Employee { Id = 68, FirstName = "Elizabeth", LastName = "Hicks", Email = "elizabeth.hicks68@hotmail.com", Position = "Project Manager" },
    new Employee { Id = 69, FirstName = "Joshua", LastName = "Clay", Email = "joshua.clay69@yahoo.com", Position = "Project Manager" },
    new Employee { Id = 70, FirstName = "Tara", LastName = "Williams", Email = "tara.williams70@hotmail.com", Position = "Business Analyst" },
    new Employee { Id = 71, FirstName = "Sheila", LastName = "Davidson", Email = "sheila.davidson71@yahoo.com", Position = "Business Analyst" },
    new Employee { Id = 72, FirstName = "Bryan", LastName = "Jackson", Email = "bryan.jackson72@yahoo.com", Position = "Software Engineer" },
    new Employee { Id = 73, FirstName = "Katie", LastName = "Lopez", Email = "katie.lopez73@gmail.com", Position = "Product Owner" },
    new Employee { Id = 74, FirstName = "Debbie", LastName = "Velazquez", Email = "debbie.velazquez74@yahoo.com", Position = "System Administrator" },
    new Employee { Id = 75, FirstName = "Kelly", LastName = "Caldwell", Email = "kelly.caldwell75@hotmail.com", Position = "Project Manager" },
    new Employee { Id = 76, FirstName = "Tanya", LastName = "York", Email = "tanya.york76@hotmail.com", Position = "System Administrator" },
    new Employee { Id = 77, FirstName = "Joseph", LastName = "Cook", Email = "joseph.cook77@hotmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 78, FirstName = "Wendy", LastName = "Barry", Email = "wendy.barry78@yahoo.com", Position = "Technical Writer" },
    new Employee { Id = 79, FirstName = "Juan", LastName = "Robinson", Email = "juan.robinson79@hotmail.com", Position = "Business Analyst" },
    new Employee { Id = 80, FirstName = "Logan", LastName = "Lewis", Email = "logan.lewis80@yahoo.com", Position = "Project Manager" },
    new Employee { Id = 81, FirstName = "Derrick", LastName = "Wright", Email = "derrick.wright81@hotmail.com", Position = "Business Analyst" },
    new Employee { Id = 82, FirstName = "Anthony", LastName = "Ortega", Email = "anthony.ortega82@gmail.com", Position = "Product Owner" },
    new Employee { Id = 83, FirstName = "Janice", LastName = "Monroe", Email = "janice.monroe83@gmail.com", Position = "UX Designer" },
    new Employee { Id = 84, FirstName = "Mark", LastName = "Houston", Email = "mark.houston84@gmail.com", Position = "Technical Writer" },
    new Employee { Id = 85, FirstName = "Daniel", LastName = "Harding", Email = "daniel.harding85@hotmail.com", Position = "QA Engineer" },
    new Employee { Id = 86, FirstName = "Julie", LastName = "Miller", Email = "julie.miller86@gmail.com", Position = "QA Engineer" },
    new Employee { Id = 87, FirstName = "Nicholas", LastName = "King", Email = "nicholas.king87@gmail.com", Position = "System Administrator" },
    new Employee { Id = 88, FirstName = "Jessica", LastName = "Williamson", Email = "jessica.williamson88@gmail.com", Position = "UX Designer" },
    new Employee { Id = 89, FirstName = "Mary", LastName = "Acevedo", Email = "mary.acevedo89@gmail.com", Position = "Data Analyst" },
    new Employee { Id = 90, FirstName = "Samantha", LastName = "Ortiz", Email = "samantha.ortiz90@yahoo.com", Position = "UX Designer" },
    new Employee { Id = 91, FirstName = "Melissa", LastName = "Davis", Email = "melissa.davis91@hotmail.com", Position = "Business Analyst" },
    new Employee { Id = 92, FirstName = "Samantha", LastName = "Reese", Email = "samantha.reese92@hotmail.com", Position = "DevOps Engineer" },
    new Employee { Id = 93, FirstName = "Sara", LastName = "Davis", Email = "sara.davis93@gmail.com", Position = "Business Analyst" },
    new Employee { Id = 94, FirstName = "Nicholas", LastName = "Holloway", Email = "nicholas.holloway94@gmail.com", Position = "QA Engineer" },
    new Employee { Id = 95, FirstName = "Christopher", LastName = "Rios", Email = "christopher.rios95@gmail.com", Position = "QA Engineer" },
    new Employee { Id = 96, FirstName = "Melissa", LastName = "Jenkins", Email = "melissa.jenkins96@yahoo.com", Position = "Product Owner" },
    new Employee { Id = 97, FirstName = "Amanda", LastName = "Rivera", Email = "amanda.rivera97@yahoo.com", Position = "Project Manager" },
    new Employee { Id = 98, FirstName = "Christopher", LastName = "Carter", Email = "christopher.carter98@gmail.com", Position = "UX Designer" },
    new Employee { Id = 99, FirstName = "Alan", LastName = "Martinez", Email = "alan.martinez99@yahoo.com", Position = "Business Analyst" },
    new Employee { Id = 100, FirstName = "Katelyn", LastName = "Moore", Email = "katelyn.moore100@gmail.com", Position = "DevOps Engineer" }

           );
        }
    }
}
